config:

  # Database specific configuration
  db:
    # The path to the directory where kits should be stored
    path: "./kits"

    # If set to true, pretty printing will be used for the database
    pretty-print: true

    # The interval (in seconds) to save the db cache to disk
    save-cache: 7200